import { AvailabilityStatus, Product } from './product.types'
import { GetProductsQueryDTO } from './validators/getProductsValidator'

let MOCK_DATA: Product[] = [
    {
        id: 1,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 2,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 3,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 4,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 5,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 6,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 7,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 8,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 9,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 10,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 11,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 12,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 13,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 14,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 15,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 16,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 17,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 18,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 19,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 12,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 21,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 22,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 23,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 24,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 25,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 26,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 27,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 28,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 29,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
    {
        id: 30,
        title: 'Essence Mascara Lash Princess',
        description:
            'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
        category: 'beauty',
        price: 9.99,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5,
        tags: ['beauty', 'mascara'],
        brand: 'Essence',
        sku: 'RCH45Q1A',
        weight: 2,
        dimensions: {
            width: 23.17,
            height: 14.43,
            depth: 28.01,
        },
        warrantyInformation: '1 month warranty',
        shippingInformation: 'Ships in 1 month',
        availabilityStatus: AvailabilityStatus.IN_STOCK,
        reviews: [
            {
                rating: 2,
                comment: 'Very unhappy with my purchase!',
                date: new Date(),
                reviewerName: 'John Doe',
                reviewerEmail: 'john.doe@x.dummyjson.com',
            },
            {
                rating: 2,
                comment: 'Not as described!',
                date: new Date(),
                reviewerName: 'Nolan Gonzalez',
                reviewerEmail: 'nolan.gonzalez@x.dummyjson.com',
            },
            {
                rating: 5,
                comment: 'Very satisfied!',
                date: new Date(),
                reviewerName: 'Scarlett Wright',
                reviewerEmail: 'scarlett.wright@x.dummyjson.com',
            },
        ],
        returnPolicy: '30 days return policy',
        minimumOrderQuantity: 24,
        meta: {
            createdAt: new Date(),
            updatedAt: new Date(),
            barcode: '9164035109868',
            qrCode: '...',
        },
        thumbnail: '...',
        images: ['...', '...', '...'],
    },
]

const findAll = (query: GetProductsQueryDTO): Product[] => {
    const result = MOCK_DATA
    //ADD fitlering and search here
    return result
}

const findByTitle = (title: string): Product[] => {
    return MOCK_DATA.filter((product) => product.title.includes(title))
}

const findById = (productId: number): Product | undefined => {
    return MOCK_DATA.find((product) => product.id === productId)
}

const save = (newProduct: Product): Product => {
    let maxId = -1
    MOCK_DATA.forEach((product) => {
        if (product.id > maxId) {
            maxId = product.id
        }
    })
    newProduct.id = maxId++
    MOCK_DATA.push(newProduct)
    return newProduct
}

const update = (newProduct: Product): Product => {
    MOCK_DATA.push(newProduct)
    return newProduct
}

const deleteById = (id: number) => {
    const index = MOCK_DATA.findIndex((product) => product.id === id)
    if (index) {
        MOCK_DATA.splice(index, 1)
    }
}

export default {
    findAll,
    findByTitle,
    findById,
    save,
    update,
    deleteById,
}
